import type {Slide} from './slides';

// Short spoken Serbian on screen; technical qualifications remain in notes.
export const shortCopy:Record<string,Partial<Slide>>={
  opening:{title:'Analiza kapaciteta elektrodistributivne mreže',accent:'za punjenje električnih vozila',body:'Novi Sad · simulacija i razvoj algoritama'},
  pressure:{title:'Gde i kada',accent:'punimo vozila?',body:'Raspored punjenja menja opterećenje mreže.'},
  'five-questions':{title:'Pet pitanja',accent:'',body:''},
  thesis:{title:'GridLab',accent:'Platforma za eksperimente',body:'Ispitujemo mrežu i razvijamo algoritme punjenja.'},
  model:{title:'Model mreže',accent:'Novog Sada',body:'OSM podaci i procenjene trase.'},
  configurable:{title:'Uslovi eksperimenta',accent:'',body:'Potrošnja, mreža i vozila.'},
  scenario:{title:'01 / Scenario',accent:'',body:'Postavljamo hipotezu i uslove.'},
  vehicles:{title:'02 / Vozila',accent:'',body:'Koliko energije traže i kada odlaze?'},
  strategies:{title:'03 / Strategije',accent:'',body:'Ista vozila i uslovi za svaki algoritam.'},
  review:{title:'04 / Pregled',accent:'',body:'Proverimo podešavanja i sačuvamo eksperiment.'},
  execution:{title:'Kako teče simulacija?',accent:'',body:'Proveravamo mrežu i napunjenost vozila.'},
  network:{title:'Gde je mreža opterećena?',accent:'',body:''},
  results:{title:'Rezultati eksperimenta',accent:'',body:'Potrošnja, naponi i isporučena energija.'},
  evidence:{title:'Kako ponavljamo rezultat?',accent:'',body:'Čuvamo ulaze, seme i verziju koda.'},
  hypothesis:{title:'Razvoj algoritma',accent:'',body:'Definišemo cilj, napišemo kod i proverimo ga.'},
  library:{title:'Biblioteka algoritama',accent:'',body:'Novi algoritam testiramo na istom scenariju.'},
  'tested-baselines':{title:'Od kojih strategija krećemo?',accent:'',body:''},
  'research-controllers':{title:'Pristupi iz istraživanja',accent:'',body:'Prilagodili smo ih našem simulatoru.'},
  'valley-filling-research':{title:'Valley filling',accent:'Punjenje van vrha potrošnje',body:''},
  'schneider-parallel':{title:'Paralela sa Schneiderom',accent:'Pametno upravljanje punjenjem',body:'Sličan cilj; ne tvrdimo da je algoritam isti.'},
  'research-learning':{title:'Prediktivno upravljanje i RL',accent:'',body:'Isprobani pristupi i njihovi izvori.'},
  'agent-capabilities':{title:'Šta agent može da uradi?',accent:'',body:''},
  mcp:{title:'Kako radi MCP?',accent:'',body:'Agent bira alat, simulator računa.'},
  'chat-demo':{title:'Od poruke do eksperimenta',accent:'',body:'Chat ili Codex plugin u terminalu. Veb-aplikacija nije neophodna.'},
  'agent-workflow':{title:'Brže do novog eksperimenta',accent:'',body:'Agent povezuje korake razvoja.'},
  benchmarks:{title:'Poređenje algoritama',accent:'',body:'Isti scenariji, semena i ograničenja.'},
  'benchmark-results':{title:'Rezultati benchmarka',accent:'',body:'Kapacitet, energija i status provere.'},
  'benchmark-strategy':{title:'Kako biramo strategiju?',accent:'',body:'Prvo puna usluga i mrežne granice, zatim niži vrh.'},
  gym:{title:'Simulator kao RL okruženje',accent:'',body:'Algoritam uči da raspodeli snagu.'},
  training:{title:'Kako izgleda učenje?',accent:'',body:'Ilustrativni PPO demo.'},
  'ppo-campaign':{title:'PPO obuka',accent:'',body:'Snaga po čvoru i provera na odvojenim slučajevima.'},
  'binary-training':{title:'Binarna RL obuka',accent:'',body:'REINFORCE: puni ili sačekaj.'},
  development:{title:'Šta olakšava razvoj?',accent:'',body:'Isti simulator i provere za svaku novu ideju.'},
  'case-study':{title:'Odgovori na zadatak',accent:'',body:'Rezultati i uslovi pod kojima važe.'},
  capacity:{title:'Koliko punih baterija dnevno?',accent:'',body:'Jun · idealno korišćenje svih 24 sata.'},
  'winning-algorithm':{title:'Punjenje prema kapacitetu',accent:'',body:'Junski kućni scenario: 48.000 vozila, po 14 kWh.'},
  location:{title:'Upravljano punjenje po lokaciji',accent:'',body:'Raspored prilagođavamo boravku vozila i rezervi mreže.'},
  critical:{title:'Koliko vozila puni istovremeno?',accent:'',body:'Jun · punjači od 7,4 kW.'},
  policy:{title:'Gde širiti mrežu punjača?',accent:'',body:'Na poslu i na javnim lokacijama, uz upravljanje snagom.'},
  admission:{title:'Koliko još vozila možemo da primimo?',accent:'',body:'Proveravamo slobodnu snagu i rok odlaska.'},
  repeat:{title:'Promenimo uslove',accent:'i proverimo ponovo.',body:''},
  'simulator-loop':{title:'Jedan korak simulacije',accent:'15 minuta u mreži',body:'Python i pandapower · balansirani AC proračun.'},
  'simulator-assumptions':{title:'Pretpostavke modela',accent:'',body:'Sintetička mreža, OSM podaci i procena potrošnje.'},
  'simulator-scale':{title:'Detaljniji simulator',accent:'kad imamo više resursa',body:'Potreban je adapter i nova validacija.'},
  improvements:{title:'Šta smo unapredili?',accent:'',body:''},
  repeatability:{title:'Ograničenja modela',accent:'',body:'Planski model, bez potvrde merenjima.'},
  next:{title:'Sledeći koraci',accent:'',body:''},
  conclusion:{title:'Rezultati se mogu proveriti.',accent:'Eksperimenti ponoviti.',body:'GridLab ostaje osnova za nove algoritme.'},
  sources:{title:'Izvori i dokumentacija',accent:'',body:''},
};
