import {shortCopy} from './shortCopy';
import type { AppCue } from './bridge';
import { serbianCopy } from './copy.sr';
import {researchSlides} from './researchSlides';
export type Scene = 'city' | 'stress' | 'grid' | 'district' | 'calm';
export type Slide = {
  id: string; chapter: string; title: string; accent?: string; body: string;
  kind: 'hero' | 'city' | 'flow' | 'app' | 'question' | 'bars' | 'compare' | 'limits' | 'closing' | 'mcp-demo';
  scene?: Scene; items?: string[]; cue?: AppCue; label?: string;
  note: string; source?: string; question?: string;
  references?: {label:string;url:string}[];
};
const baseSlides: Slide[] = [
  {id:'opening',chapter:'The challenge',title:'More EVs.',accent:'The same grid.',body:'How did we investigate the charging challenge—and make the next experiment easier to repeat?',kind:'hero',scene:'city',label:'NOVI SAD · EV CHARGING RESEARCH',note:'Opening, about 10 seconds. Introduce the challenge: accommodating more charging without assuming new network assets. The city is a stylized rendering of synthetic demand points, not surveyed buildings.',source:'docs/models/novi-sad.md'},
  {id:'pressure',chapter:'The challenge',title:'Charging is a question of',accent:'where. when. how.',body:'The same fleet can create very different local loads. Timing and placement matter as much as total energy.',kind:'city',scene:'stress',items:['Location','Arrival & departure','Control strategy'],note:'About 10 seconds. Animated vehicles and colors explain the concept; they are illustrative, not a replay of a measured overload.'},
  {id:'five-questions',chapter:'The challenge',title:'Five questions.',accent:'One investigation.',body:'Capacity. Location. Simultaneity. Charging strategy. Admission.',kind:'flow',scene:'grid',items:['How many EVs?','Where can they charge?','When do limits bind?','Which strategy helps?','What can we admit now?'],note:'Finish the 30-second problem introduction. These are the five challenge questions from the supplied assignment. The provided load curves are fictional scenario inputs, not city telemetry.'},
  {id:'thesis',chapter:'Our approach',title:'Build the experiment.',accent:'Keep the evidence.',body:'GridLab brings model assumptions, charging strategies and evaluation into one research workflow.',kind:'hero',scene:'calm',label:'THE PLATFORM',note:'Our contribution is both the case study and the reusable workflow. Standardized refers to shared project contracts, not an external certification.'},
  {id:'model',chapter:'Our approach',title:'Start with a model',accent:'you can inspect.',body:'OSM geography → synthetic service points → inferred feeders → electrical checks.',kind:'city',scene:'grid',items:['2,648 synthetic points','9 primary stations','Explicit provenance'],note:'The detailed reference model has 2,648 synthetic loads. The experiment simulator uses a reduced representation. Do not imply that every detailed feeder is simulated in every experiment. Only three primary coordinates are name-confirmed in OSM.',source:'docs/models/novi-sad.md'},
  {id:'configurable',chapter:'Our approach',title:'Change the assumptions.',accent:'Keep the comparison fair.',body:'Demand, electrical budgets, vehicle behavior and controller settings define the experiment.',kind:'app',cue:{view:'experiments',step:0},label:'CONFIGURABLE EXPERIMENT',note:'Show the actual configuration controls. Network replacement is an engineering/model integration step, not an established one-click importer. Avoid implying arbitrary model import is already implemented.',source:'docs/gui-workflow.md'},
  {id:'scenario',chapter:'Repeatable experiments',title:'01 / Scenario',accent:'Set the conditions.',body:'Choose the demand scenario and operating assumptions. State the hypothesis before looking at results.',kind:'app',cue:{view:'experiments',step:0},label:'SCENARIO → VEHICLES → STRATEGIES → REVIEW',note:'Explain normal and stress demand, capacity overrides and scenario provenance. The iframe is the real app. No experiment is started by advancing slides.'},
  {id:'vehicles',chapter:'Repeatable experiments',title:'02 / Vehicles',accent:'Describe the demand.',body:'Fleet size, placement, energy requests, charger power and parking windows.',kind:'app',cue:{view:'experiments',step:1},label:'SCENARIO → VEHICLES → STRATEGIES → REVIEW',note:'Advance within the same mounted experiment form. Show how arrival and departure define scheduling flexibility. Keep the draft unchanged unless deliberately interacting.'},
  {id:'strategies',chapter:'Repeatable experiments',title:'03 / Strategies',accent:'Compare the decisions.',body:'Apply competing charging policies to the same scenario and seeded sessions.',kind:'app',cue:{view:'experiments',step:2},label:'SCENARIO → VEHICLES → STRATEGIES → REVIEW',note:'Select the registered controllers you want to discuss. Matched sessions help control variability; the electrical and service criteria remain the basis for acceptance.'},
  {id:'review',chapter:'Repeatable experiments',title:'04 / Review',accent:'Freeze the question.',body:'Inspect the complete definition. A saved experiment records exactly what was requested.',kind:'app',cue:{view:'experiments',step:3},label:'SCENARIO → VEHICLES → STRATEGIES → REVIEW',note:'Explain Save only versus Save & run. Saving makes an immutable definition. The deck never clicks either button for you.',source:'docs/gui-workflow.md'},
  {id:'execution',chapter:'Repeatable experiments',title:'One run.',accent:'Every interval matters.',body:'Simulate charging, solve the network, record constraints, and check energy by departure.',kind:'flow',items:['Saved definition','Charging actions','AC power flow','Constraint checks','Recorded evidence'],label:'132 × 15-MINUTE INTERVALS IN THE REPORTED HOME STUDY',note:'The reported home-charging study covers 132 quarter-hour intervals, including overnight departure tails. Animation shows execution stages; it does not start a live worker.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'network',chapter:'Repeatable experiments',title:'See the electrical',accent:'consequences.',body:'Connect a system-level number to the supply and delivery hierarchy.',kind:'app',cue:{view:'network'},label:'THE REDUCED EXPERIMENT NETWORK',note:'Explain the reduction from the detailed geographic model to the simulator. This is a synthetic planning proxy, not the as-built EDS grid.'},
  {id:'results',chapter:'Repeatable experiments',title:'Results that answer',accent:'the original question.',body:'Inspect demand, voltage, loading and delivered energy together.',kind:'app',cue:{view:'results',section:'Summary'},label:'SAVED RUN · SELECTABLE IN PRESENTATION SETTINGS',note:'Select a completed saved run in the deck settings before presenting. If none exists, the app shows its honest empty state. The latest completed live run is selected by default. This demonstration is separate from the frozen direct study.'},
  {id:'local-results',chapter:'Repeatable experiments',title:'Find the constraint.',accent:'Follow it through time.',body:'Move from the summary to the network and district evidence without losing the selected run.',kind:'app',cue:{view:'results',section:'Network'},label:'SUMMARY → NETWORK',note:'The same app instance and run remain loaded. Use the app timeline if you want to inspect individual intervals.'},
  {id:'evidence',chapter:'Repeatable experiments',title:'A result needs',accent:'a record.',body:'Inputs, seed, implementation identity, run status and acceptance evidence travel with the finding.',kind:'app',cue:{view:'results',section:'Evidence'},label:'RESULT → PROVENANCE',note:'Repeatability requires compatible inputs and implementation. A fresh clone still needs the cached OSM source snapshot to reproduce the detailed reference bit-for-bit.',source:'docs/reproducibility.md'},
  {id:'hypothesis',chapter:'Faster development',title:'The next algorithm starts',accent:'with a hypothesis.',body:'Make the objective, observations, constraints and fallback explicit before implementation.',kind:'flow',items:['Propose','Specify','Build','Compare','Challenge & revise'],note:'The registered strategy workflow preserves proposal and specification records. BUILD prepares a coding handoff; actual implementation requires the explicit coding workflow.',source:'docs/strategy-development.md'},
  {id:'library',chapter:'Faster development',title:'Reuse the experiment.',accent:'Change the controller.',body:'The strategy workspace connects algorithm specifications to a shared evaluation workflow.',kind:'app',cue:{view:'strategies',section:'library'},label:'CONTROLLER LIBRARY & DEVELOPMENT WORKFLOW',note:'Show controller cards and the structured command editor. Avoid saying that saving a proposal automatically implements Python.',source:'docs/strategy-development.md'},
  {id:'assistant',chapter:'Faster development',title:'AI assists.',accent:'Tools leave evidence.',body:'Use the assistant and typed MCP operations to inspect, specify and compare experiments.',kind:'app',cue:{view:'strategies',section:'development',chat:true},label:'AI + MODEL CONTEXT PROTOCOL',note:'This opens the actual assistant without sending a message. MCP is Model Context Protocol; MPC is model predictive control. They are different. Tool evidence supports claims; an assistant response alone does not establish a result.',source:'docs/agent-contract.md'},
  {id:'benchmarks',chapter:'Faster development',title:'Compare on',accent:'shared ground.',body:'Frozen scenarios, matched seeds, common constraints and explicit completion status.',kind:'app',cue:{view:'benchmarks'},label:'BENCHMARK WORKSPACE',note:'Show the saved-suite workflow. Slide navigation starts no benchmark. The later evidence slides use the separate completed direct study; its inputs are distinct from this live benchmark workspace.',source:'docs/benchmark.md'},
  {id:'gym',chapter:'Faster development',title:'The same problem.',accent:'A learning environment.',body:'An RL policy observes the state, proposes charging budgets and receives feedback from the simulator.',kind:'flow',items:['Observe grid & sessions','Choose node budgets','Simulate one interval','Evaluate reward','Repeat & evaluate'],label:'RL GYM · CONTINUOUS NODE CONTROL',note:'Current continuous PPO supplies 52 node power budgets. Explain observation/action/reward rather than promising performance. Evaluation on held-out cases is separate from training.',source:'docs/continuous-rl.md'},
  {id:'training',chapter:'Faster development',title:'Train. Inspect.',accent:'Then challenge it.',body:'Track learning and compare held-out behavior with existing controllers.',kind:'app',cue:{view:'rl'},label:'TRAINING WORKSPACE · DEMO DATA REMAINS LABELLED',note:'The PPO showcase includes illustrative demo fixtures. They are not evidence of a trained improvement. Current documentation establishes no RL superiority.',source:'docs/continuous-rl.md'},
  {id:'development',chapter:'Faster development',title:'Less repeated setup.',accent:'More testable ideas.',body:'Reuse the scenario, controller interface, evaluator and comparison machinery.',kind:'flow',items:['Shared simulator','Typed tools','Saved experiments','Matched comparisons'],note:'This is the mechanism for faster development. We have not measured end-to-end development speedup, so do not claim a percentage.'},
  {id:'case-study',chapter:'The five answers',title:'What did the',accent:'investigation show?',body:'Question → approach → evidence → conclusion → next experiment.',kind:'hero',scene:'grid',label:'NOVI SAD CASE STUDY',note:'Transition back to the assignment. The following charts use the newer completed direct study, with frozen inputs and three seeds, rather than the superseded provisional benchmark. They are separate from the currently selected live run.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'capacity',chapter:'The five answers',question:'01 / HOW MANY EVs?',title:'Coordination changes',accent:'the tested boundary.',body:'On the June reference day, 13,000 home-charging EVs pass with immediate charging; 48,000 pass with capacity-aware charging.',kind:'bars',label:'FROZEN DIRECT STUDY · THREE SEEDS · CONDITIONAL RESULTS',note:'June home charging, primary operation: 1.02 pu source, no non-EV demand shifting. All three seeds pass at 13,000 immediate and 48,000 capacity-aware; the next sampled failures are 13,500 and 48,500. These are sampled daily participation bounds, not exact real-city maxima. Winter zero-EV baseline violations prevent year-round certification.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'location',chapter:'The five answers',question:'02 / WHERE DO THEY CHARGE?',title:'Timing and placement',accent:'change the answer.',body:'Matched energy requests still produce different demand profiles when availability and electrical placement change.',kind:'compare',scene:'district',label:'FROZEN DIRECT STUDY · THREE SEEDS · CONDITIONAL RESULTS',note:'The new direct study compares home, workplace, public and mixed sessions at 1,000 vehicles and 14,000 battery kWh. All seeds pass. Home supply peak is 149.02–149.24 MW; work 145.41 MW; public 146.61–146.76 MW. Public uses ten assumed hubs, so timing and location must be separated; same-node controls are also provided. These frozen study windows differ from the subsequently added whole-day app profile.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'critical',chapter:'The five answers',question:'03 / WHEN DO LIMITS BIND?',title:'A daily fleet is not',accent:'a simultaneous count.',body:'At 7.4 kW per charger, the tested June city placement admits 10,044 full-power cars at 03:00, but 6,516 at 20:00.',kind:'limits',items:['Fix time, placement & charger power','Recheck the safe count and next failure','Daily service is a separate constraint'],note:'Direct study integer snapshots: June city, 7.4 kW: 03:00 safe 10,044 / next 10,045; 20:00 safe 6,516 / next 6,517. LV aggregate binds. These counts depend on the allocation and adopted budgets; they are not measured city limits. Distinguish electrical failure, unmet energy and numerical uncertainty.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'policy',chapter:'The five answers',question:'04 / WHICH STRATEGY HELPS?',title:'Test the policy',accent:'in its context.',body:'At 10,000 home EVs, randomized delay serves all requests at a 145.41 MW peak; a fixed 23:00 start fails grid checks on all three seeds.',kind:'question',items:['Compare at matched fleet sizes','Check service before peak','Retest across scenarios & seeds'],note:'Matched 10,000-EV study: immediate 182.49–183.29 MW, randomized delay 145.41 MW, valley filling 153.77–153.87 MW; all serve 140,000 battery kWh and pass 3/3 seeds. Fixed delay peaks at 201.68–201.70 MW and fails 3/3 despite zero unmet energy. Scheduling protection and fallback differ by controller. This does not establish a universal best policy.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'admission',chapter:'The five answers',question:'05 / WHAT CAN WE ADMIT NOW?',title:'Available power now',accent:'is only half the answer.',body:'Include committed charging, test added power, refine the feasible boundary—and retain the departure requirement.',kind:'flow',items:['Current commitments','Proposed extra kW','AC & capacity checks','Refine safe point','Schedule to departure'],note:'Instantaneous admission is documented separately from the saved benchmark. At 7.4 kW and 90% efficiency, one hour supplies only 6.66 kWh; headroom cannot overcome insufficient dwell time.',source:'artifacts/challenge-study-v2/report-final.md'},
  {id:'repeat',chapter:'The five answers',title:'Change an assumption.',accent:'Repeat the experiment.',body:'A useful answer includes the conditions under which it holds—and a path to test the next case.',kind:'app',cue:{view:'experiments',step:0},label:'BACK TO THE SAME RESEARCH WORKFLOW',note:'Return to the actual experiment draft. Propose changing workplace windows or testing another district as the next experiment. Keep these new hypotheses distinct from the reported cases.'},
  {id:'improvements',chapter:'Simulation & next steps',title:'Improve the simulation.',accent:'Preserve the question.',body:'Better accounting and a scalable representation make experiments more useful.',kind:'flow',items:['Demand + loss reconciliation','Full departure horizon','Compatible vehicle cohorts','Whole-day charging profiles'],note:'Vehicle aggregation preserves node/deadline/energy classes but can change greedy scheduling behavior. New whole-day profiles add home/work/public shares and complete departure horizons. The 100-car smoke checks validate execution, not maximum capacity. Fresh profiles need fresh benchmark evidence. Timing diagnostics are indicative, not certified equal-policy speedup.',source:'docs/node-aggregation.md'},
  {id:'repeatability',chapter:'Simulation & next steps',title:'Repeatable does not mean',accent:'assumption-free.',body:'Preserve inputs and code identity. Report failures. Keep model limitations visible.',kind:'limits',items:['Synthetic network & inferred routes','Source snapshot required for full rebuild','Winter baseline prevents annual certification'],note:'The detailed reference is an internally consistent planning proxy. Cached OSM data is not fully distributed. The new direct study supersedes provisional historical capacity claims. Preserve winter baseline failures and conditional interpretation.',source:'docs/reproducibility.md'},
  {id:'next',chapter:'Simulation & next steps',title:'The next experiments',accent:'are already questions.',body:'Extend the evidence before extending the claims.',kind:'flow',items:['Measured demand calibration','Measured charging behavior','Detailed LV & phase behavior','More seeds & independent reruns'],note:'These are proposed future improvements and research directions, not implemented capabilities or completed findings.'},
  {id:'conclusion',chapter:'Conclusion',title:'We investigated five questions.',accent:'We built a way to ask more.',body:'Inspect the assumptions. Repeat the experiment. Develop and test the next solution.',kind:'closing',scene:'calm',label:'GRIDLAB · QUESTIONS TO EVIDENCE',note:'Close on the two contributions: a qualified case study and a reusable development and evaluation workflow. Invite the audience to inspect the live application.'},
  {id:'sources',chapter:'Appendix',title:'The evidence',accent:'behind the story.',body:'The case study, model provenance and workflow documentation remain inspectable.',kind:'question',items:['Completed five-question direct study','Novi Sad model & reproducibility','Strategy development & agent contract','Benchmark protocol & continuous RL'],note:'Primary local sources: artifacts/challenge-study-v2/report-final.md; docs/models/novi-sad.md; docs/reproducibility.md; docs/strategy-development.md; docs/agent-contract.md; docs/benchmark.md; docs/continuous-rl.md. Geographic data © OpenStreetMap contributors, ODbL. Upstream methodology: Gebhard, Tundis and Steinke (2024).',source:'docs/models/novi-sad.md'},
];
const agentSlides: Slide[] = [
  {id:'agent-capabilities',chapter:'LLM agent i MCP',title:'Šta agent',accent:'može da uradi?',body:'Od pripreme eksperimenta do tumačenja rezultata.',kind:'flow',items:['Pregleda dokumentaciju','Priprema scenarije','Implementira i testira','Analizira rezultate'],note:'Agent ima alate za pregled, specifikaciju algoritama, scenarije, pokretanje i poređenje. Pisanje koda je poseban, izričito izabran postupak Implement sa sačuvanom specifikacijom. Uspešan poziv alata nije dokaz naučnog poboljšanja.',source:'docs/agent-contract.md'},
  {id:'mcp',chapter:'LLM agent i MCP',title:'Kako poruka',accent:'postaje eksperiment?',body:'LLM bira korake. MCP povezuje alate. Simulator računa.',kind:'flow',items:['Tvoj zahtev','LLM agent','MCP alati','Simulator','Sačuvani rezultat'],note:'LLM razume zahtev i planira pozive, a MCP prenosi strukturisane zahteve alatima platforme. Postoje alati ev_propose_strategy, ev_specify_strategy, ev_save_scenario, ev_prepare_experiment i ev_verify_strategy. Kod se implementira u radnom prostoru; MCP ne izvršava proizvoljan kod iz poruke.',source:'docs/agent-contract.md'},
];
const chatSlides: Slide[] = [
  {id:'chat-demo',chapter:'LLM agent i MCP',title:'Zahtev → alat → rezultat.',body:'Isti alati kroz chat ili Codex plugin u terminalu. Veb-aplikacija ne mora da bude otvorena.',kind:'mcp-demo',note:'Rekonstruisan primer razgovora, ne snimak stvarne LLM sesije. Prikazuje skraćene MCP argumente i stvarne identifikatore pripremljenog eksperimenta. Ne šalje poruke i ne pokreće alate.',source:'docs/agent-contract.md'},
  {id:'agent-workflow',chapter:'LLM agent i MCP',title:'Manje ručnog povezivanja.',accent:'Brže do provere ideje.',body:'Agent koristi isti postupak za algoritme i eksperimente.',kind:'flow',items:['Hipoteza','Specifikacija','Kod i testovi','Eksperiment','Poređenje'],note:'Ubrzanje proizlazi iz ponovne upotrebe modela, alata, definicija i provera. Agent pomaže da se ovi koraci povežu, ali svaki rezultat mora imati odgovarajuću evidenciju. Ukupno ubrzanje razvoja nije mereno i ne navodimo procenat.',source:'docs/strategy-development.md'},
];
export const slides: Slide[] = baseSlides.flatMap(slide => {
  const localized = { ...slide, ...serbianCopy[slide.id] };
  if(slide.id==='library')return [localized,...researchSlides];
  if(slide.id==='network')return [localized,
    {id:'simulator-loop',chapter:'Kako radi simulator',title:'Jedan korak.',accent:'Petnaest minuta u mreži.',body:'Python i pandapower računaju balansirani AC tok snaga.',kind:'flow',items:['Osnovna potrošnja','Dolazak i odlazak EV','Odluka algoritma','AC tok snaga','Energija i ograničenja'],note:'Simulator kombinuje sezonsku krivu osnovne potrošnje sa snagom punjača u čvorovima. U svakom koraku računa napone, opterećenja i gubitke, ažurira preostalu energiju i prati rokove odlaska. Završetak obuhvata i poslednje odlaske posle nominalnog dana.',source:'docs/models/ev-playground.md'},
    {id:'simulator-assumptions',chapter:'Kako radi simulator',title:'Šta model',accent:'pretpostavlja?',body:'Planerski model Novog Sada, izveden iz OSM podataka i procena potrošnje.',kind:'limits',items:['Sintetička mreža i sesije','Balansiran sistem · konstantno PQ','Korak 15 min · bez tranzijenata'],note:'Model nije snimak izvedene EDS mreže. Nema fizičkog modela niskonaponskih vodova, neuravnoteženosti faza ili harmonika. Agregatne granice nizvodnih nivoa su posebne pretpostavke; viša rezolucija zahteva i kvalitetnije ulaze.',source:'docs/models/ev-playground.md'},
    {id:'simulator-scale',chapter:'Kako radi simulator',title:'Više resursa.',accent:'Detaljnija provera.',body:'Isti tok istraživanja može da se poveže sa zahtevnijim simulatorom.',kind:'flow',items:['Brzi redukovani model','Detaljne kontrolne tačke','Adapter za novi simulator','Nova validacija'],note:'Već postoji detailed_check za odabrane snimke na detaljnom pandapower modelu. Reset/step interfejs odvaja upravljanje od simulacije. Zamena celog backend-a nije gotov izbor jednim klikom: traži adapter, usklađene rezultate i ponovnu validaciju. Više compute-a omogućava duže i detaljnije provere, ali ne zamenjuje bolje podatke.',source:'docs/models/ev-playground.md'}] as Slide[];
  if(slide.id==='capacity')return [{...localized,source:'docs/presentation-daily-energy.md'},
    {id:'winning-algorithm',chapter:'Odgovori na zadatak',title:'Za više vozila:',accent:'punjenje prema kapacitetu.',body:'U ispitanom junskom kućnom scenariju: 48.000 naspram 13.000 uz trenutno punjenje.',kind:'flow',items:['Ko uskoro odlazi?','Koliko energije nedostaje?','Koliko mreža dopušta?','Dodeli snagu i proveri AC'],note:'Capacity-aware je heuristika sa prioritetom odlaska i centralnom proverom raspoloživog kapaciteta i AC ograničenja. Najveći prolazni ispitani dnevni broj u ovom poređenju je 48.000; naredna ispitana tačka 48.500 ne prolazi. Za minimum vrha pri 10.000 vozila bolji rezultat u završenoj studiji ima randomized_delay (145,41 MW). Ne postoji dokaz univerzalnog pobednika svih strategija i sezona.',source:'artifacts/challenge-study-v2/report-final.md'}] as Slide[];
  if (slide.id === 'assistant') return [...agentSlides, ...chatSlides];
  if (slide.id === 'benchmarks') return [{...localized,cue:{view:'benchmarks',section:'setup'}},
    {id:'benchmark-results',chapter:'Benčmark i izbor strategije',title:'Isti uslovi.',accent:'Vidljive razlike.',body:'Otvori ćeliju: kapacitet, energija, ograničenja i status provere.',kind:'app',cue:{view:'benchmarks',section:'results'},note:'Prikaži sačuvanu matricu i otvori rezultat. Status failed/cancelled ili nepotpune ćelije ostaju vidljivi. Istorijska matrica nije konačan rang; promena izvornog koda je poništila završnu proveru starog posla.',source:'docs/benchmark.md'},
    {id:'benchmark-strategy',chapter:'Benčmark i izbor strategije',title:'Kako biramo',accent:'sledeću strategiju?',body:'Najpre isporučena energija i granice mreže. Zatim vrh i vreme računanja.',kind:'flow',items:['Isti scenario i seme','Potpuna isporuka','Bez kršenja granica','Niži vrh','Ponovljena provera'],note:'Benčmark otkriva gde algoritam zaostaje. Zatim pripremamo hipotezu, implementaciju i ponovnu proveru na zamrznutim uslovima. Nema univerzalnog pobednika iz nepotpune matrice.',source:'docs/benchmark.md'}] as Slide[];
  if (slide.id === 'training') return [{...localized,cue:{view:'rl',section:'demo'}},
    {id:'ppo-campaign',chapter:'Učenje strategije',title:'PPO: koliko snage',accent:'dodeliti svakom čvoru?',body:'Kontinualne akcije, sačuvane kontrolne tačke i provera na odvojenim slučajevima.',kind:'app',cue:{view:'rl',section:'campaign'},note:'Prikaz stvarnih kampanja i njihovog statusa. Animirani PPO demo na prethodnom slajdu je ilustracija; kampanja i benchmark su odvojena evidencija. Ne tvrdimo da je PPO nadmašio ostale strategije.',source:'docs/continuous-rl.md'},
    {id:'binary-training',chapter:'Učenje strategije',title:'Binarni RL:',accent:'uključi ili sačekaj.',body:'REINFORCE uči odluku po punjaču. Pratimo nagradu, energiju i kršenja granica.',kind:'app',cue:{view:'rl',section:'legacy'},note:'Binarni REINFORCE je raniji prototip sa on/off akcijama. Razlikuje se od kontinualnog PPO-a po akcijama i treningu; trenirana politika zahteva izdvojenu evaluaciju. Prikaz sam ne pokreće trening.',source:'docs/continuous-rl.md'}] as Slide[];
  return [localized];
}).map(slide=>({...slide,...shortCopy[slide.id],note:slide.note+(['location','policy'].includes(slide.id)?' Predlog rešenja: upravljanje po lokaciji, korisnički rok odlaska, noćni prozor samo kada je izvodljiv, raspodela tokom radnog dana i ograničavanje snage javnih punjača. Zaseban SN priključak može rasteretiti postojeći NN ogranak, ali zahteva novu trafostanicu/priključak, proveru uzvodnih granica i novu simulaciju. Više punjača daje fleksibilnost samo uz upravljanje ukupnom snagom. Postojeći model ne računa rezervu svakog stvarnog distributivnog transformatora; proverava modelovane ekvivalente i zbirna ograničenja na 15 minuta.':'')}));
