// Uses bundled Playwright (NODE_PATH); real local HTTP server with an explicit fake CLI.
const {chromium}=require('../web/node_modules/playwright');
const {spawn}=require('child_process');
const path=require('path');
const fs=require('fs');
const assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const python=process.env.EV_TEST_PYTHON || path.join(root,'.venv',process.platform==='win32'?'Scripts/python.exe':'bin/python');
const server=spawn(python,[path.join(root,'tests/chat_browser_fixture.py')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
const checks=[];
const delay=ms=>new Promise(r=>setTimeout(r,ms));
let browser;
(async()=> {
  const url=await new Promise((resolve,reject)=> {
    let buffer=''; const timer=setTimeout(()=>reject(Error('Fixture startup timed out')),30000);
    server.stdout.on('data',chunk=> {buffer+=chunk; if(buffer.includes('\n')) {clearTimeout(timer);resolve(JSON.parse(buffer.split('\n')[0]).url);}});
    server.stderr.on('data',chunk=>process.stderr.write(chunk));
    server.on('exit',code=>reject(Error(`Fixture exited: ${code}`)));
  });
  browser=await chromium.launch({headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1000}});
  const page=await context.newPage();
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  await page.getByRole('button',{name:'Codex CLI chat'}).click();
  const composer=page.getByLabel('Message to Codex');
  const send=page.getByRole('button',{name:'Send message',exact:true});
  async function ready() {await page.waitForFunction(()=>document.querySelector('button[aria-label="Send message"]')?.disabled===false,{},{timeout:15000});}
  async function sendText(text) {await composer.fill(text);await ready();await send.click();}
  await sendText('repeat');
  await page.getByText('Fixture answer: repeat',{exact:true}).waitFor();
  await sendText('repeat');
  await page.waitForFunction(()=>[...document.querySelectorAll('.event.assistant p')].filter(e=>e.textContent==='Fixture answer: repeat').length===2);
  assert.equal(await page.locator('.event.user p').filter({hasText:/^repeat$/}).count(),2);
  assert.equal(await page.locator('.event.assistant p').count(),2);
  assert.deepEqual(await page.locator('.event.user p,.event.assistant p').allTextContents(),['repeat','Fixture answer: repeat','repeat','Fixture answer: repeat']);
  checks.push('Repeated messages, answer deduplication, chronology, reused CLI item IDs');
  const link=page.getByRole('link',{name:'Open full evidence'}).first();
  const output=await (await page.request.get(new URL(await link.getAttribute('href'),url).href)).json();
  assert.equal(output.item.result.payload.length,50000);
  checks.push('Full large tool evidence remains retrievable');
  await sendText('slow reload');
  await page.getByRole('button',{name:'Cancel chat response'}).waitFor();
  await page.reload();
  await page.getByRole('button',{name:'Codex CLI chat'}).click();
  await page.getByText('slow reload',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Cancel chat response'}).waitFor();
  assert.equal(await send.isDisabled(),true);
  checks.push('Reload restores active conversation and cancellation');
  const second=await page.context().newPage();
  await second.goto(url); await second.getByRole('button',{name:'Codex CLI chat'}).click();
  await second.getByText('slow reload',{exact:true}).waitFor();
  await second.close(); checks.push('Second tab recovers active conversation');
  await page.getByRole('button',{name:'Minimize chat'}).click();
  await page.getByRole('button',{name:'Codex CLI chat'}).click();
  await page.getByRole('button',{name:'Cancel chat response'}).click();
  await composer.fill('after cancel');await ready();
  assert.equal(await page.getByRole('status').innerText(),'cancelled');
  await send.click();await page.getByText('Fixture answer: after cancel',{exact:true}).waitFor();
  checks.push('Minimize preserves work; cancellation settles before next send');
  let lost=false;
  await page.route('**/api/chat',async route=> {
    if(route.request().method()==='POST'&&!lost) {lost=true;await route.fetch();await route.abort('connectionreset');}
    else await route.continue();
  });
  await sendText('lost response');
  await page.getByText('Fixture answer: lost response',{exact:true}).waitFor();
  assert.equal(await page.locator('.event.user p').filter({hasText:/^lost response$/}).count(),1);
  await page.unroute('**/api/chat'); checks.push('Lost accepted POST response recovers without duplicating work');
  await sendText('slow reconnect');
  await page.getByText('slow reconnect',{exact:true}).waitFor();
  let failed=false;
  await page.route('**/api/chat/chat-*',async route=> {
    if(route.request().method()==='GET'&&!failed) {failed=true;await route.abort('connectionreset');}
    else await route.continue();
  });
  await page.getByRole('status').filter({hasText:'reconnecting'}).waitFor();
  assert.equal(await send.isDisabled(),true);
  await page.unroute('**/api/chat/chat-*');
  await page.getByRole('status').filter({hasText:'running'}).waitFor();
  await page.route('**/api/chat/*/cancel',route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Fixture cancellation failure'})}));
  await page.getByRole('button',{name:'Cancel chat response'}).click();
  await page.getByRole('alert').filter({hasText:'Cancellation could not be confirmed'}).waitFor();
  assert.equal(await send.isDisabled(),true);
  await page.unroute('**/api/chat/*/cancel');
  checks.push('Failed cancellation stays observable and does not enable sending');
  await page.getByRole('button',{name:'Cancel chat response'}).click();
  await composer.fill('next');await ready();checks.push('Transient polling failure remains busy and reconnects');
  await page.getByRole('button',{name:'New conversation',exact:true}).click();
  await sendText('fresh conversation');await page.getByText('Fixture answer: fresh conversation',{exact:true}).waitFor();
  assert.equal(await page.locator('.event.user p').count(),1);
  await page.reload();await page.getByRole('button',{name:'Codex CLI chat'}).click();
  await page.getByText('Fixture answer: fresh conversation',{exact:true}).waitFor();checks.push('New conversation and completed conversation restoration');
  await composer.fill('Explain benchmark results');await ready();
  await page.getByLabel('Chat workflow').selectOption('explain');
  const request=page.waitForRequest(r=>r.url().endsWith('/api/chat')&&r.method()==='POST');
  await send.click();const body=(await request).postDataJSON();
  assert.equal(body.requested_action,'explain');assert.equal(body.contract_version,'1.0.0');
  await page.getByText('Fixture answer: Explain benchmark results',{exact:true}).waitFor();
  await composer.fill('Can you implement this saved strategy?');await ready();
  assert.equal(await page.getByLabel('Chat workflow').inputValue(),'auto');
  await page.getByLabel('Chat workflow').selectOption('implement');
  await page.getByLabel('Saved specification ID').fill('invalid-specification');
  await send.click();
  await page.getByRole('alert').filter({hasText:'Implementation requires a saved specification ID'}).waitFor();
  assert.equal(await composer.inputValue(),'Can you implement this saved strategy?');
  await page.getByLabel('Chat workflow').selectOption('auto');
  checks.push('Workflow and version sent, scope resets, invalid implementation ID rejected without losing draft');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(root,'artifacts/playground/evidence/chat-recovery-mobile.png')});
  const box=await page.locator('.chat').boundingBox();assert(box.x>=0 && box.x+box.width<=390);
  checks.push('Mobile chat fits viewport');assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,backend:'real HTTP with fake CLI JSONL',checks,page_errors:errors},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();});
